name: Job Pipeline

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSLMODE: ${{ secrets.DB_SSLMODE }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_KEY: ${{ secrets.APP_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bronze ingestion
        run: python ingestion/adzuna_ingest.py

      - name: Run Silver transformation
        run: python transformation/silver_transform.py

      - name: Run Gold aggregation
        run: python gold/gold_transform.py
